# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/egor/code/apps/clion-2017.2.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/egor/code/apps/clion-2017.2.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/egor/neko8

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/egor/neko8

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/egor/code/apps/clion-2017.2.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/egor/code/apps/clion-2017.2.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/egor/neko8/CMakeFiles /home/egor/neko8/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/egor/neko8/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named neko8

# Build rule for target.
neko8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 neko8
.PHONY : neko8

# fast build rule for target.
neko8/fast:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/build
.PHONY : neko8/fast

src/api.o: src/api.cpp.o

.PHONY : src/api.o

# target to build an object file
src/api.cpp.o:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/api.cpp.o
.PHONY : src/api.cpp.o

src/api.i: src/api.cpp.i

.PHONY : src/api.i

# target to preprocess a source file
src/api.cpp.i:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/api.cpp.i
.PHONY : src/api.cpp.i

src/api.s: src/api.cpp.s

.PHONY : src/api.s

# target to generate assembly for a file
src/api.cpp.s:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/api.cpp.s
.PHONY : src/api.cpp.s

src/carts.o: src/carts.cpp.o

.PHONY : src/carts.o

# target to build an object file
src/carts.cpp.o:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/carts.cpp.o
.PHONY : src/carts.cpp.o

src/carts.i: src/carts.cpp.i

.PHONY : src/carts.i

# target to preprocess a source file
src/carts.cpp.i:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/carts.cpp.i
.PHONY : src/carts.cpp.i

src/carts.s: src/carts.cpp.s

.PHONY : src/carts.s

# target to generate assembly for a file
src/carts.cpp.s:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/carts.cpp.s
.PHONY : src/carts.cpp.s

src/fs.o: src/fs.cpp.o

.PHONY : src/fs.o

# target to build an object file
src/fs.cpp.o:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/fs.cpp.o
.PHONY : src/fs.cpp.o

src/fs.i: src/fs.cpp.i

.PHONY : src/fs.i

# target to preprocess a source file
src/fs.cpp.i:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/fs.cpp.i
.PHONY : src/fs.cpp.i

src/fs.s: src/fs.cpp.s

.PHONY : src/fs.s

# target to generate assembly for a file
src/fs.cpp.s:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/fs.cpp.s
.PHONY : src/fs.cpp.s

src/graphics.o: src/graphics.cpp.o

.PHONY : src/graphics.o

# target to build an object file
src/graphics.cpp.o:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/graphics.cpp.o
.PHONY : src/graphics.cpp.o

src/graphics.i: src/graphics.cpp.i

.PHONY : src/graphics.i

# target to preprocess a source file
src/graphics.cpp.i:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/graphics.cpp.i
.PHONY : src/graphics.cpp.i

src/graphics.s: src/graphics.cpp.s

.PHONY : src/graphics.s

# target to generate assembly for a file
src/graphics.cpp.s:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/graphics.cpp.s
.PHONY : src/graphics.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/neko.o: src/neko.cpp.o

.PHONY : src/neko.o

# target to build an object file
src/neko.cpp.o:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/neko.cpp.o
.PHONY : src/neko.cpp.o

src/neko.i: src/neko.cpp.i

.PHONY : src/neko.i

# target to preprocess a source file
src/neko.cpp.i:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/neko.cpp.i
.PHONY : src/neko.cpp.i

src/neko.s: src/neko.cpp.s

.PHONY : src/neko.s

# target to generate assembly for a file
src/neko.cpp.s:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/neko.cpp.s
.PHONY : src/neko.cpp.s

src/ram.o: src/ram.cpp.o

.PHONY : src/ram.o

# target to build an object file
src/ram.cpp.o:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/ram.cpp.o
.PHONY : src/ram.cpp.o

src/ram.i: src/ram.cpp.i

.PHONY : src/ram.i

# target to preprocess a source file
src/ram.cpp.i:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/ram.cpp.i
.PHONY : src/ram.cpp.i

src/ram.s: src/ram.cpp.s

.PHONY : src/ram.s

# target to generate assembly for a file
src/ram.cpp.s:
	$(MAKE) -f CMakeFiles/neko8.dir/build.make CMakeFiles/neko8.dir/src/ram.cpp.s
.PHONY : src/ram.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... neko8"
	@echo "... src/api.o"
	@echo "... src/api.i"
	@echo "... src/api.s"
	@echo "... src/carts.o"
	@echo "... src/carts.i"
	@echo "... src/carts.s"
	@echo "... src/fs.o"
	@echo "... src/fs.i"
	@echo "... src/fs.s"
	@echo "... src/graphics.o"
	@echo "... src/graphics.i"
	@echo "... src/graphics.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/neko.o"
	@echo "... src/neko.i"
	@echo "... src/neko.s"
	@echo "... src/ram.o"
	@echo "... src/ram.i"
	@echo "... src/ram.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

